package io.yiduspace.community.model;

import java.util.ArrayList;
import java.util.List;

public class NotificationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notification
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notification
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notification
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public NotificationExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table notification
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andReplierIsNull() {
            addCriterion("replier is null");
            return (Criteria) this;
        }

        public Criteria andReplierIsNotNull() {
            addCriterion("replier is not null");
            return (Criteria) this;
        }

        public Criteria andReplierEqualTo(Long value) {
            addCriterion("replier =", value, "replier");
            return (Criteria) this;
        }

        public Criteria andReplierNotEqualTo(Long value) {
            addCriterion("replier <>", value, "replier");
            return (Criteria) this;
        }

        public Criteria andReplierGreaterThan(Long value) {
            addCriterion("replier >", value, "replier");
            return (Criteria) this;
        }

        public Criteria andReplierGreaterThanOrEqualTo(Long value) {
            addCriterion("replier >=", value, "replier");
            return (Criteria) this;
        }

        public Criteria andReplierLessThan(Long value) {
            addCriterion("replier <", value, "replier");
            return (Criteria) this;
        }

        public Criteria andReplierLessThanOrEqualTo(Long value) {
            addCriterion("replier <=", value, "replier");
            return (Criteria) this;
        }

        public Criteria andReplierIn(List<Long> values) {
            addCriterion("replier in", values, "replier");
            return (Criteria) this;
        }

        public Criteria andReplierNotIn(List<Long> values) {
            addCriterion("replier not in", values, "replier");
            return (Criteria) this;
        }

        public Criteria andReplierBetween(Long value1, Long value2) {
            addCriterion("replier between", value1, value2, "replier");
            return (Criteria) this;
        }

        public Criteria andReplierNotBetween(Long value1, Long value2) {
            addCriterion("replier not between", value1, value2, "replier");
            return (Criteria) this;
        }

        public Criteria andRecipientIsNull() {
            addCriterion("recipient is null");
            return (Criteria) this;
        }

        public Criteria andRecipientIsNotNull() {
            addCriterion("recipient is not null");
            return (Criteria) this;
        }

        public Criteria andRecipientEqualTo(Long value) {
            addCriterion("recipient =", value, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientNotEqualTo(Long value) {
            addCriterion("recipient <>", value, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientGreaterThan(Long value) {
            addCriterion("recipient >", value, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientGreaterThanOrEqualTo(Long value) {
            addCriterion("recipient >=", value, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientLessThan(Long value) {
            addCriterion("recipient <", value, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientLessThanOrEqualTo(Long value) {
            addCriterion("recipient <=", value, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientIn(List<Long> values) {
            addCriterion("recipient in", values, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientNotIn(List<Long> values) {
            addCriterion("recipient not in", values, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientBetween(Long value1, Long value2) {
            addCriterion("recipient between", value1, value2, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientNotBetween(Long value1, Long value2) {
            addCriterion("recipient not between", value1, value2, "recipient");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNull() {
            addCriterion("question_id is null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNotNull() {
            addCriterion("question_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdEqualTo(Long value) {
            addCriterion("question_id =", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotEqualTo(Long value) {
            addCriterion("question_id <>", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThan(Long value) {
            addCriterion("question_id >", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThanOrEqualTo(Long value) {
            addCriterion("question_id >=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThan(Long value) {
            addCriterion("question_id <", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThanOrEqualTo(Long value) {
            addCriterion("question_id <=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIn(List<Long> values) {
            addCriterion("question_id in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotIn(List<Long> values) {
            addCriterion("question_id not in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdBetween(Long value1, Long value2) {
            addCriterion("question_id between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotBetween(Long value1, Long value2) {
            addCriterion("question_id not between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andNotificationTypeIsNull() {
            addCriterion("notification_type is null");
            return (Criteria) this;
        }

        public Criteria andNotificationTypeIsNotNull() {
            addCriterion("notification_type is not null");
            return (Criteria) this;
        }

        public Criteria andNotificationTypeEqualTo(Integer value) {
            addCriterion("notification_type =", value, "notificationType");
            return (Criteria) this;
        }

        public Criteria andNotificationTypeNotEqualTo(Integer value) {
            addCriterion("notification_type <>", value, "notificationType");
            return (Criteria) this;
        }

        public Criteria andNotificationTypeGreaterThan(Integer value) {
            addCriterion("notification_type >", value, "notificationType");
            return (Criteria) this;
        }

        public Criteria andNotificationTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("notification_type >=", value, "notificationType");
            return (Criteria) this;
        }

        public Criteria andNotificationTypeLessThan(Integer value) {
            addCriterion("notification_type <", value, "notificationType");
            return (Criteria) this;
        }

        public Criteria andNotificationTypeLessThanOrEqualTo(Integer value) {
            addCriterion("notification_type <=", value, "notificationType");
            return (Criteria) this;
        }

        public Criteria andNotificationTypeIn(List<Integer> values) {
            addCriterion("notification_type in", values, "notificationType");
            return (Criteria) this;
        }

        public Criteria andNotificationTypeNotIn(List<Integer> values) {
            addCriterion("notification_type not in", values, "notificationType");
            return (Criteria) this;
        }

        public Criteria andNotificationTypeBetween(Integer value1, Integer value2) {
            addCriterion("notification_type between", value1, value2, "notificationType");
            return (Criteria) this;
        }

        public Criteria andNotificationTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("notification_type not between", value1, value2, "notificationType");
            return (Criteria) this;
        }

        public Criteria andNotificationStatusIsNull() {
            addCriterion("notification_status is null");
            return (Criteria) this;
        }

        public Criteria andNotificationStatusIsNotNull() {
            addCriterion("notification_status is not null");
            return (Criteria) this;
        }

        public Criteria andNotificationStatusEqualTo(Integer value) {
            addCriterion("notification_status =", value, "notificationStatus");
            return (Criteria) this;
        }

        public Criteria andNotificationStatusNotEqualTo(Integer value) {
            addCriterion("notification_status <>", value, "notificationStatus");
            return (Criteria) this;
        }

        public Criteria andNotificationStatusGreaterThan(Integer value) {
            addCriterion("notification_status >", value, "notificationStatus");
            return (Criteria) this;
        }

        public Criteria andNotificationStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("notification_status >=", value, "notificationStatus");
            return (Criteria) this;
        }

        public Criteria andNotificationStatusLessThan(Integer value) {
            addCriterion("notification_status <", value, "notificationStatus");
            return (Criteria) this;
        }

        public Criteria andNotificationStatusLessThanOrEqualTo(Integer value) {
            addCriterion("notification_status <=", value, "notificationStatus");
            return (Criteria) this;
        }

        public Criteria andNotificationStatusIn(List<Integer> values) {
            addCriterion("notification_status in", values, "notificationStatus");
            return (Criteria) this;
        }

        public Criteria andNotificationStatusNotIn(List<Integer> values) {
            addCriterion("notification_status not in", values, "notificationStatus");
            return (Criteria) this;
        }

        public Criteria andNotificationStatusBetween(Integer value1, Integer value2) {
            addCriterion("notification_status between", value1, value2, "notificationStatus");
            return (Criteria) this;
        }

        public Criteria andNotificationStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("notification_status not between", value1, value2, "notificationStatus");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Long value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Long value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Long value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Long value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Long value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Long value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Long> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Long> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Long value1, Long value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Long value1, Long value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table notification
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 23 15:18:06 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table notification
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}