package io.yiduspace.community.model;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.id
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.replier
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    private Long replier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.recipient
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    private Long recipient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.question_id
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notification_type
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    private Integer notificationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notification_status
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    private Integer notificationStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.gmt_create
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.id
     *
     * @return the value of notification.id
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.id
     *
     * @param id the value for notification.id
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.replier
     *
     * @return the value of notification.replier
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public Long getReplier() {
        return replier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.replier
     *
     * @param replier the value for notification.replier
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public void setReplier(Long replier) {
        this.replier = replier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.recipient
     *
     * @return the value of notification.recipient
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public Long getRecipient() {
        return recipient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.recipient
     *
     * @param recipient the value for notification.recipient
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public void setRecipient(Long recipient) {
        this.recipient = recipient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.question_id
     *
     * @return the value of notification.question_id
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.question_id
     *
     * @param questionId the value for notification.question_id
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notification_type
     *
     * @return the value of notification.notification_type
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public Integer getNotificationType() {
        return notificationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notification_type
     *
     * @param notificationType the value for notification.notification_type
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public void setNotificationType(Integer notificationType) {
        this.notificationType = notificationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notification_status
     *
     * @return the value of notification.notification_status
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public Integer getNotificationStatus() {
        return notificationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notification_status
     *
     * @param notificationStatus the value for notification.notification_status
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public void setNotificationStatus(Integer notificationStatus) {
        this.notificationStatus = notificationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.gmt_create
     *
     * @return the value of notification.gmt_create
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.gmt_create
     *
     * @param gmtCreate the value for notification.gmt_create
     *
     * @mbg.generated Wed Jun 23 15:18:06 CST 2021
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}