CREATE TABLE USER
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_ID BIGINT,
    NAME VARCHAR(50),
    TOKEN VARCHAR(36),
    GMT_CREATE BIGINT,
    GMT_MODIFIED BIGINT,
    bio VARCHAR(256) NULL,
    avatar_url varchar(100) null
);
